"""initial migration

Revision ID: 46afb86b9b87
Revises: 
Create Date: 2025-07-10 17:28:15.747590

"""
from typing import Sequence, Union
import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46afb86b9b87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('members')
    op.drop_table('sermons')
    op.drop_table('family_members')
    op.drop_table('event')
    op.drop_table('families')
    op.add_column(
        'user',
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text(f"'{datetime.datetime.utcnow().isoformat()}'"))
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.create_table('families',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('family_name', sa.VARCHAR(), nullable=False),
    sa.Column('head_of_family_id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['head_of_family_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('preacher', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('family_id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('relationship', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sermons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('preacher', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('video_url', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=6), nullable=False),
    sa.Column('marital_status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('occupation', sa.VARCHAR(), nullable=True),
    sa.Column('emergency_contact', sa.VARCHAR(), nullable=True),
    sa.Column('emergency_contact_phone', sa.VARCHAR(), nullable=True),
    sa.Column('baptism_date', sa.DATE(), nullable=True),
    sa.Column('membership_date', sa.DATE(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.Column('house_address', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('profile_image', sa.VARCHAR(), nullable=True),
    sa.Column('join_date', sa.DATE(), nullable=False),
    sa.Column('verification_code', sa.VARCHAR(), nullable=True),
    sa.Column('verification_code_expires', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    # ### end Alembic commands ###
